version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  socketio-server-1:
    build: .
    container_name: socketio-server-1
    volumes:
    - ./server.js:/usr/src/app/server.js:ro
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - SEND_MESSAGE=true

  socketio-server-2:
    build: .
    container_name: socketio-server-2
    volumes:
    - ./server.js:/usr/src/app/server.js:ro
    ports:
      - "3001:3000"
    depends_on:
      - redis

  socketio-client:
    build: .
    container_name: socketio-client
    command: node client.js
    # command: sleep infinity
    volumes:
    - ./client.js:/usr/src/app/client.js:ro
    
