# REF: https://uptrace.dev/get/config.html

ch:
  addr: clickhouse:9000
  user: ${CLICKHOUSE_USER}
  password: ${CLICKHOUSE_PASSWORD}
  database: ${CLICKHOUSE_DB}

pg:
  addr: postgres:5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}

projects:
  - id: 1
    name: SWAG
    token: ${UPTRACE_PROJECT_TOKEN}

auth:
  users:
    - name: Anonymous
      email: uptrace@localhost
      password: uptrace
