version: '3.8'

x-defaults: &defaults
  env_file: .env
x-environment: &environment
  FOO: BAR

services:
  srs:
    image: ossrs/srs:v5
    command: /usr/local/srs/objs/srs -c conf/srt.conf
    volumes:
    - ./srt.conf:/usr/local/srs/conf/srt.conf
    ports:
    - "8080:8080"
    - "1935:1935"
    - "1985:1985"
    - "10080:10080/udp"
    << : *defaults
  