apiVersion: v1
kind: Pod
metadata:
  name: nino-test
  labels:
    app: nino-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    # resources:
    #   requests:
    #     cpu: "0.2"
    #   limits:
    #     cpu: "1"
    ports:
    - name: nginx 
      containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nino-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: nginx
                port:
                  number: 80
