apiVersion: v1
kind: Service
metadata:
  namespace: soketi
  name: soketi
spec:
  selector:
    app: soketi-server
  ports:
    - name: http
      protocol: TCP
      port: 6001
      targetPort: 6001
