apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: soketi-server
  namespace: soketi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soketi-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: soketi-worker
  namespace: soketi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soketi-worker
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
