apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gclb
  namespace: soketi
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  tls:
  - secretName: nino.baby.tls
    hosts:
    - nino.baby
  defaultBackend:
    service:
      name: soketi
      port:
        name: http
