apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # volumes:
      # - name: vol
      #   persistentVolumeClaim:
      #     claimName: dev-pvc
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        # volumeMounts:
        # - name: vol
        #   mountPath: /tmp/persistent
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: dev-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi


