# MEAN
# mongo
# express
# angular
# nodejs

version: "3.9"
volumes:
  mongo-unixsocket:
services:
  mongo:
    image: mongo:5.0.3
    volumes:
      - ./tmp:/tmp
      - ./mongod.conf:/etc/mongod.conf
    user: 999:999
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    volumes:
      - ./tmp:/tmp
    depends_on:
      - mongo
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@%2Ftmp%2Fmongodb-27017.sock
  # frontend:
  #   image: nginx
# volumes:
#   logvolume01: {}
