version: '3.6'

services:
  api: 
    build: .
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8000', '--reload']
    # env_file:
    #   - .env
    volumes: 
    - ./:/usr/src/app
    ports:
      - 8000:8000
