ARG         base=python:3.11.3-alpine3.17


FROM        ${base} AS poetry
ARG         POETRY_VERSION=1.4.0

ENV         POETRY_VERSION=${POETRY_VERSION}

RUN         apk add --no-cache --virtual .build-deps \
                curl \
                build-base \
                libffi-dev && \
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/install-poetry.py | python && \
            apk del .build-deps

###

FROM        ${base} AS builder
WORKDIR     /usr/src/app

ENV         PATH=/root/.local/bin:$PATH
ENV         POETRY_VIRTUALENVS_CREATE=false
ENV         PIP_DISABLE_PIP_VERSION_CHECK=on

COPY        --from=poetry /root/.local /root/.local

COPY        pyproject.toml .
COPY        poetry.lock .

RUN         apk add --no-cache --virtual .build-deps && \
            poetry install -vv -n --only=main --no-root && \
            # Whitelist removal
            find /usr/local -type f -name "*.pyc" -delete && \
            find /usr/local -type f -name "*.pyo" -delete && \
            find /usr/local -type d -name "__pycache__" -delete && \
            find /usr/local -type d -name "tests" -exec rm -rf '{}' + && \
            apk del .build-deps

###

FROM        ${base}

WORKDIR     /usr/src/app

ENV         PYTHONUNBUFFERED=1

EXPOSE      8000/tcp
CMD         ["flask", "run", "--host", "0.0.0.0"]


COPY        --from=poetry /root/.local /root/.local
COPY        --from=builder /usr/local /usr/local
COPY        . /usr/src/app
