apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  labels:
    app: debug
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      imagePullSecrets:
          - name: nino-ghcr
      containers:
      - name: app
        image: ghcr.io/swaglive/swag-webapp:sha-b397c8c
        env: 
        - name: HOSTNAME
          value: '0.0.0.0'
        - name: NODE_OPTIONS
          value: --max-old-space-size=8192
        - name: PM2__NEXTJS__SCALE
          value: 2'
        - name: PM2__NEXTJS__MAX_MEMORY_RESTART
          value: 1500M
        - name: PM2__LEGACY_APP__MAX_MEMORY_RESTART
          value: 1000M
        - name: PM2__LEGACY_APP__SCALE
          value: '2'
        - name: REDIS_URL
          value: redis://cache-t/0?max_connections=25&socket_connect_timeout=5
        - name: LEGACY_SSR_SENTRY_TRACE_SAMPLE_RATE
          value: '0.25'
        - name: LEGACY_SSR_SENTRY_PROFILE_SAMPLE_RATE
          value: '0.25'
        - name: LEGACY_SSR_SENTRY_PROFILE_SAMPLE_RATE_REQUEST_HANDLER
          value: '0.25'
        - name: NEXTJS_SSR_SENTRY_TRACE_SAMPLE_RATE
          value: '0.25'
        - name: NEXTJS_SSR_SENTRY_PROFILE_SAMPLE_RATE
          value: '0.25'
      - name: nginx
        # image: nginx:1.25.4-alpine
        image: ghcr.io/swaglive/nginx:1.25.4-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
        - name: config
          subPath: default.conf
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true
        - name: config
          subPath: nginx.js
          mountPath: /etc/nginx/nginx.js
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: app

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: debug
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  PUBLIC_URL_PREFIX: https://public.swag.live
  WATCH_URL_PREFIX: https://watch.swag.live
  default.conf: |
    upstream app {
      server                                  127.0.0.1:3000;

      zone                                    app 64k;

      keepalive                               16;
      keepalive_requests                      100000;
      keepalive_time                          10m;
      keepalive_timeout                       10s;
    }

    upstream legacy {
      server                                  127.0.0.1:3001;

      zone                                    legacy 64k;

      keepalive                               16;
      keepalive_requests                      100000;
      keepalive_time                          10m;
      keepalive_timeout                       10s;
    }

    map $uri $cache_control {
      default                                 "public, max-age=900, s-maxage=600, stale-while-revalidate=3600, stale-if-error=3600, immutable";
      /                                       "public, max-age=600, s-maxage=300, stale-while-revalidate=3600, stale-if-error=3600, immutable";
      "~^/(creator)/"                         "public, max-age=3600, s-maxage=300, stale-while-revalidate=2592000, immutable";
      "~\.(jpg|png|css|js|svg|webp|ico)$"     "public, max-age=2592000, stale-while-revalidate=2592000, immutable";
      "~\.(html)$"                            "public, max-age=3600, stale-while-revalidate=2592000, immutable";
      "~^/(js|img|locale)/"                   "public, max-age=2592000, stale-while-revalidate=2592000, immutable";
      "~^/static/"                            "public, max-age=2592000, stale-while-revalidate=2592000, immutable";
      "~^/campaigns/"                         "public, max-age=3600, stale-while-revalidate=2592000, stale-if-error=2592000, immutable";
      /sitemap.xml                            "public, max-age=600, stale-while-revalidate=2592000, immutable";
      /robots.txt                             "public, max-age=600, stale-while-revalidate=2592000, immutable";
      /oAuthLogin.html                        "private, max-age=60";
    }

    server {
      listen                                  80;

      js_import                               nginx.js;

      root                                    /usr/share/nginx/html;

      rewrite                                 ^/(favicon.ico)$ /static/img/$1 last;
      rewrite                                 ^/(apple-touch-icon.png)$ /static/img/$1 last;
      rewrite                                 ^/(apple-touch-icon-120x120.png)$ /static/img/$1 last;
      rewrite                                 ^/(apple-touch-icon-precomposed.png)$ /static/img/$1 last;
      rewrite                                 ^/(apple-touch-icon-120x120-precomposed.png)$ /static/img/$1 last;
      rewrite                                 ^/(img|js|locale)/(.*) /static/$1/$2 last;
      rewrite                                 ^/(workbox-.*)$ /static/sw/$1 last;
      rewrite                                 ^/(swag-service-worker.*)$ /static/sw/$1 last;
      rewrite                                 ^/_next/(.*) /static/_next/$1 last;

      rewrite                                 ^/undefined$ /404 permanent;

      location @storage {
        root                                  /data/swag.live;
      }

      location = /oAuthLogin.html {
      }

      location ~* '^/(.well-known|static|creator)/' {
        rewrite                               ^/creator/$ /creator/index.html last;
        try_files                             $uri @storage;
      }

      location /ads/ {
        root                                  /data;
      }

      location /campaigns/ {
        proxy_cache_key                       ${host}${uri}?_feed=${arg__feed}&_filters=${arg__filters}&_sorts=${arg__sorts};
        proxy_pass                            http://app;
      }

      location / {
        proxy_pass                            http://app;
      }
    }  

  nginx.conf: |
    load_module             modules/ngx_http_js_module.so;
    load_module             modules/ngx_http_brotli_filter_module.so;
    load_module             modules/ngx_http_brotli_static_module.so;
    load_module             modules/ngx_http_zstd_filter_module.so;
    load_module             modules/ngx_http_zstd_static_module.so;
    load_module             modules/ngx_http_headers_more_filter_module.so;

    user                    nginx;
    worker_processes        4;
    worker_cpu_affinity     auto;

    error_log               /var/log/nginx/error.log notice;
    pid                     /var/run/nginx.pid;

    events {
      worker_connections    16384;
      use                   epoll;
    }

    http {
      include               mime.types;
      default_type          application/octet-stream;

      map $upstream_cache_status $upstream_cache_status_short {
        default                                       -;
        MISS                                          M;
        BYPASS                                        B;
        EXPIRED                                       E;
        STALE                                         S;
        UPDATING                                      U;
        REVALIDATED                                   R;
        HIT                                           H;
      }

      map $uri $service_worker_allowed {
        default                               "";
        "~^/static/sw/"                       "/";
        "~^/swag-service-worker"              "/";
      }

      log_format                              main '[$upstream_cache_status_short][$status][${request_time}s] $request_method $request_uri "$http_user_agent"';

      proxy_cache_path                        /var/cache/nginx levels=1:2 keys_zone=cache:128m inactive=10m max_size=64G;
      # Enable persistent upstream connections
      proxy_http_version                      1.1;
      proxy_set_header                        Connection "";
      proxy_set_header                        Host $host;
      # NOTE: Re-use uncompressed response as cache
      proxy_set_header                        Accept-Encoding "";
      proxy_set_header                        X-Forwarded-Proto https;
      proxy_set_header                        X-Forwarded-Host $host;
      proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;

      # Enable proxy caching
      proxy_cache                             cache;
      proxy_cache_key                         ${host}${proxy_host}${uri}${is_args}${args};

      proxy_cache_valid                       404 1s;
      proxy_cache_use_stale                   updating;
      proxy_cache_revalidate                  on;
      proxy_cache_background_update           on;
      proxy_cache_lock                        on;
      proxy_cache_lock_age                    5s;
      proxy_cache_lock_timeout                10s;
      proxy_cache_convert_head                on;

      proxy_ignore_headers                    Set-Cookie Vary;
      proxy_hide_header                       "Set-Cookie";

      access_log                              /var/log/nginx/access.log main;

      # Brotli
      brotli                                  on;
      brotli_static                           on;
      brotli_comp_level                       6;
      brotli_min_length                       256;
      brotli_types                            text/css
                                              text/plain
                                              text/javascript
                                              application/javascript
                                              application/json
                                              application/x-javascript
                                              application/xml
                                              application/xml+rss
                                              application/xhtml+xml
                                              application/x-font-ttf
                                              application/x-font-opentype
                                              application/vnd.ms-fontobject
                                              image/svg+xml
                                              image/x-icon
                                              application/rss+xml
                                              application/atom_xml
                                              application/vnd.apple.mpegURL
                                              application/x-mpegurl
                                              vnd.apple.mpegURL
                                              application/dash+xml;

      # GZIP
      gzip                                    on;
      gzip_static                             on;
      gzip_vary                               on;
      gzip_disable                            "msie6";
      gzip_min_length                         512;
      gzip_proxied                            any;
      gzip_comp_level                         6;
      gzip_buffers                            16 8k;
      gzip_types                              text/css
                                              text/plain
                                              text/javascript
                                              application/javascript
                                              application/json
                                              application/x-javascript
                                              application/xml
                                              application/xml+rss
                                              application/xhtml+xml
                                              application/x-font-ttf
                                              application/x-font-opentype
                                              application/vnd.ms-fontobject
                                              image/svg+xml
                                              image/x-icon
                                              image/vnd.microsoft.icon
                                              application/rss+xml
                                              application/atom_xml
                                              application/vnd.apple.mpegURL
                                              application/x-mpegurl
                                              vnd.apple.mpegURL
                                              application/dash+xml;

      # zstd
      zstd                                    on;
      zstd_static                             on;
      zstd_min_length                         256;
      zstd_comp_level                         9;
      zstd_types                              text/css
                                              text/plain
                                              text/javascript
                                              application/javascript
                                              application/json
                                              application/x-javascript
                                              application/xml
                                              application/xml+rss
                                              application/xhtml+xml
                                              application/x-font-ttf
                                              application/x-font-opentype
                                              application/vnd.ms-fontobject
                                              image/svg+xml
                                              image/x-icon
                                              image/vnd.microsoft.icon
                                              application/rss+xml
                                              application/atom_xml
                                              application/vnd.apple.mpegURL
                                              application/x-mpegurl
                                              vnd.apple.mpegURL
                                              application/dash+xml;

      sendfile                                on;
      aio                                     on;
      directio                                4m;
      directio_alignment                      512;
      open_file_cache                         max=4096 inactive=10m;
      open_file_cache_valid                   10m;
      open_file_cache_min_uses                10;
      open_file_cache_errors                  on;
      tcp_nopush                              on;
      tcp_nodelay                             on;
      keepalive_timeout                       600;
      keepalive_requests                      100;
      send_timeout                            10s;

      absolute_redirect                       off;

      more_set_headers                        -s '200 301 302 307 308' "Cache-Control: ${cache_control}";
      more_set_headers                        -s '200' "Service-worker-allowed: ${service_worker_allowed}";

      include                                 conf.d/*.conf;
    }
  nginx.js: |
    export default { };
  no_proxy: localhost,127.0.0.1,127.0.0.0,127.0.1.1,127.0.1.1,local.home
