apiVersion: v1
kind: ConfigMap
metadata:
  name: nats
  namespace: soketi
data:
  nats.conf: |
    server_name: $POD_NAME

    # Log
    # debug:   true
    # trace:   true
    logtime: true

    # Client listener
    port: 4222
    
    # HTTP monitoring
    http: 8222

    # Cluster config for HA
    cluster {
      name: nats-cluster
      port: 6222
      routes = [
        "nats://nats-0.nats.soketi.svc.cluster.local:6222",
        "nats://nats-1.nats.soketi.svc.cluster.local:6222",
        "nats://nats-2.nats.soketi.svc.cluster.local:6222"
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 30
    }
    
    jetstream {
      store_dir: "/data"
      max_memory_store: 1G
      max_file_store: 10G
    }

