apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: soketi
  labels:
    app: nats
spec:
  clusterIP: None
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: cluster
      port: 6222
      targetPort: cluster
    - name: monitor
      port: 8222
      targetPort: monitor
