version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./certs/server/server.crt:/etc/ssl/server.crt
    - ./certs/server/server.key:/etc/ssl/server.key
    - ./certs/ca.crt:/etc/nginx/client_certs/ca.crt

  api:
    image: a901002666/sentry-example
    command: flask run --host 0.0.0.0 -p 8080 --reload
    ports:
    - "8080:8080"
    volumes:
    - ./app.py:/usr/src/app/app.py
