apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: default
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  advanced:
      horizontalPodAutoscalerConfig:
        name: keda-hpa-nginx-deployment
  minReplicaCount: 4   # Can be 0 if you want to scale to zero
  maxReplicaCount: 10
  pollingInterval: 15  # How often to check Redis (in seconds)
  cooldownPeriod: 300  # How long to wait before scaling back down
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: redis
    metadata:
      address: redis.default.svc.cluster.local:6379
      listName: mylist
      listLength: "5"
      enableTLS: "false"
